<a href="https://colab.research.google.com/github/Ansubasnet-creator/2510322_ansu/blob/main/worksheet1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Problem 1
import numpy as np
# 1
a = np.array([[1,2],[3,4]])
print(a)
# 2
b = np.ones((4,2))
print(b)
# 3
c = np.full((2,2),4)
print(c)
# 4
d = np.zeros_like(a)
print(d)
# 5
e = np.ones_like(a)
print(e)
# 6
new_list = [1,2,3,4]
arr = np.array(new_list)
print(arr)

[[1 2]
 [3 4]]
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[[4 4]
 [4 4]]
[[0 0]
 [0 0]]
[[1 1]
 [1 1]]
[1 2 3 4]


In [ ]:
# problem2
import numpy as np
arr = np.arange(10,50)
print(arr)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [ ]:
import numpy as np
arr = np.arange(0,9)
print(arr)
matrix = arr.reshape(3,3)
print(matrix)

[0 1 2 3 4 5 6 7 8]
[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:

import numpy as np

identity_matrix = np.eye(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
import numpy as np

arr = np.random.random(30)
mean_value = arr.mean()

print("Array:", arr)
print("Mean:", mean_value)

Array: [0.91259188 0.38360134 0.39721397 0.26571404 0.94332491 0.2611542
 0.69272604 0.41364625 0.64644583 0.1267056  0.15641004 0.16765507
 0.91391878 0.7110603  0.52865331 0.2855941  0.87312072 0.27475421
 0.38742038 0.58373101 0.95442874 0.64830229 0.57007444 0.63599921
 0.73436194 0.16229437 0.06385162 0.39573886 0.0954252  0.72687417]
Mean: 0.49709309491119513


In [ ]:
import numpy as np

arr = np.random.random((10,10))

print(arr)

min = arr.min()
max = arr.max()

print("Minimum value: ",min)
print("Maximum value: ",max)

[[0.31459288 0.99589774 0.36647569 0.58174322 0.55937535 0.7554353
  0.19145196 0.63464727 0.26197315 0.38369595]
 [0.78329748 0.67791888 0.7705761  0.73481172 0.54525955 0.97748733
  0.61941567 0.58578403 0.36234879 0.15945564]
 [0.28045367 0.58855461 0.70765114 0.92285405 0.66470944 0.72124026
  0.44753794 0.16652155 0.76983389 0.59802392]
 [0.46354955 0.59636499 0.52134671 0.69841924 0.19159715 0.40411203
  0.28925054 0.59935078 0.66718641 0.51132138]
 [0.20450913 0.81657021 0.29866128 0.58272679 0.52896409 0.46635822
  0.63287093 0.07396587 0.48975921 0.43248915]
 [0.38077268 0.61362232 0.78116816 0.09207816 0.47722062 0.36377974
  0.38818785 0.95545871 0.30362838 0.92504478]
 [0.83935291 0.60770078 0.44909697 0.01930684 0.64889209 0.89519667
  0.80186942 0.32976168 0.24405884 0.42716733]
 [0.74638446 0.81672434 0.9338803  0.33794299 0.97737762 0.81220134
  0.8329138  0.75908089 0.60900592 0.41437222]
 [0.96070114 0.67768005 0.89175054 0.6627918  0.19027321 0.96062204
  0.47970308 

In [ ]:
import numpy as np

arr = np.zeros(10)
print(arr)
arr[4] = 1
print(arr)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [ ]:
import numpy as np

arr = [1,2,0,0,4,0]

reversed = np.flip(arr)
print(reversed)

[0 4 0 0 2 1]


In [ ]:

import numpy as np

rows, cols = 5, 5
arr = np.ones((rows, cols), dtype=int)
arr[1:-1, 1:-1] = 0

print(arr)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


In [ ]:
import numpy as np

# Create an 8x8 array filled with zeros
checkerboard = np.zeros((8, 8), dtype=int)

# Set the alternating pattern for the checkerboard
checkerboard[1::2, ::2] = 1  # odd rows, even columns
checkerboard[::2, 1::2] = 1  # even rows, odd columns

# Print the checkerboard
print(checkerboard)


[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [ ]:
import numpy as np

x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])

# 1. Add
addition = x + y
print("Addition:\n", addition)

# 2. Subtract
subtraction = x - y
print("Subtraction:\n", subtraction)

# 3. Multiplication
multiplication = x * 3
multiplication_1 = v * 2
print("Multiplication of x with 3:\n", multiplication)
print("Multiplication of v with 2:\n", multiplication_1)

# 4. Square
square_x = x ** 2
print("Square of x:\n", square_x)

# Dot product
VandW = np.dot(v, w)
print("Dot product between v and w: ", VandW)

XandV = np.dot(x, v)
print("Dot product between X and V: ", XandV)

XandY = np.dot(x, y)
print("Dot product between X and Y: \n", XandY)

# 6. Concatenation
XwithY = np.vstack((x, y))
print("Vertical stack of x and y:\n", XwithY)

VwithW = np.column_stack((v, w))
print("Column stack of v and w:\n", VwithW)

# 7. Fix concatenation error
xwithv = np.concatenate((x, v.reshape(1, -1)), axis=0)  # Reshape v to be a row vector
print("Concatenation of x and v:\n", xwithv)


Addition:
 [[ 6  8]
 [10 13]]
Subtraction:
 [[-4 -4]
 [-4 -3]]
Multiplication of x with 3:
 [[ 3  6]
 [ 9 15]]
Multiplication of v with 2:
 [18 20]
Square of x:
 [[ 1  4]
 [ 9 25]]
Dot product between v and w:  219
Dot product between X and V:  [29 77]
Dot product between X and Y: 
 [[19 22]
 [50 58]]
Vertical stack of x and y:
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]
Column stack of v and w:
 [[ 9 11]
 [10 12]]
Concatenation of x and v:
 [[ 1  2]
 [ 3  5]
 [ 9 10]]


In [ ]:
#problem4
import numpy as np

A = np.array([[3,4],[7,8]])
B = np.array([[5,3],[2,1]])

I = np.eye(2, dtype=int)

A_inv = np.linalg.inv(A)
AdotAinv = np.dot(A,A_inv)
AdotAinv_int = np.round(AdotAinv).astype(int)
print(AdotAinv_int)

if np.array_equal(AdotAinv_int, I):
    print("True")
else:
    print("False")

[[1 0]
 [0 1]]
True


In [ ]:
import numpy as np

A = np.array([[3,4],[7,8]])
B = np.array([[5,3],[2,1]])

AdotB = np.dot(A,B)
BdotA = np.dot(B,A)

print(AdotB)
print(BdotA)

if np.array_equal(AdotB, BdotA):
    print("Both are equal")
else:
    print("Not equal")

[[23 13]
 [51 29]]
[[36 44]
 [13 16]]
Not equal
